[package]
name = "sjdinsd/packet"
version = "0.1.91"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "I DO NOT OWN THIS PACKAGE. reuploaded version of 5uphi's Packet - Networking library. This package will also no longer be maintained after this initial publishing, please either urge 5uphi to maintain the package, or upload it yourself"
homepage = "https://devforum.roblox.com/t/packet-networking-library/3573907"
repository = "https://create.roblox.com/store/asset/104116977416770/Packet"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
]